name: Bug report
description: Report a reproducible defect in RelayMesh
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please fill out all fields so the team can reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce the problem.
      placeholder: |
        1. Run ...
        2. Submit ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: input
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Include OS, Java, Maven, and runtime command.
      placeholder: |
        OS:
        Java:
        Maven:
        Command:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and artifacts
      description: Paste relevant logs, stack traces, or attach files.
      render: shell
    validations:
      required: false
